import { fetchAccountCenter, updateAccountCenter } from "./app-account.js?v=1";
import { fetchMetaConnection } from "./app-meta.js?v=8";
import { getSession } from "./auth.js";
import { initAppPage, setTopbarIdentity, signOutAndRedirect, wireCommonShell } from "./app-shell.js?v=10";

const esc = (value) => String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");
const row = (label, value) => `<div class="profile-detail-row"><span>${esc(label)}</span><strong>${esc(value || "—")}</strong></div>`;
const date = (value) => { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? "—" : parsed.toLocaleString(); };

function demoSnapshot(profile) {
  return { user: { email: profile.email, createdAt: new Date(Date.now() - 7_776_000_000).toISOString() }, profile: { display_name: "Demo Workspace", company_name: "Northwind Commerce", role_title: "Growth lead", phone: "", locale: "en-US" }, workspace: { id: profile.workspaceId, name: "Northwind Commerce", role: "owner", memberCount: 3, createdAt: new Date(Date.now() - 7_776_000_000).toISOString() }, settings: { timezone: "Europe/Warsaw", currency: "USD", default_period: "30d", data_retention_days: 395 }, subscription: { status: "inactive", draft_plan_id: "growth", draft_cadence: "annual" }, verifiedPlan: null, draftPlan: { name: "Growth" }, platformAdmin: null };
}

function hydrate(snapshot, auth, meta) {
  const profile = snapshot.profile || {}; const workspace = snapshot.workspace || {}; const displayName = profile.display_name || auth.profile.displayName || "Member"; const email = snapshot.user?.email || auth.profile.email;
  document.getElementById("profile-hero-name").textContent = displayName; document.getElementById("profile-hero-email").textContent = [profile.role_title, profile.company_name, email].filter(Boolean).join(" · "); document.getElementById("profile-hero-initials").textContent = displayName.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase() || "AF";
  const fields = { "profile-display-name": displayName, "profile-company-name": profile.company_name || "", "profile-role-title": profile.role_title || "", "profile-phone": profile.phone || "", "profile-locale": profile.locale || "en-US" }; Object.entries(fields).forEach(([id, value]) => { const input = document.getElementById(id); if (input) input.value = value; }); document.getElementById("profile-email-readonly").textContent = email;
  const active = ["active", "trialing"].includes(snapshot.subscription?.status); const plan = active ? snapshot.verifiedPlan : snapshot.draftPlan;
  document.getElementById("profile-plan-card").innerHTML = `<div class="account-card__head"><span class="account-card__icon">PLAN</span><div><h2>Plan &amp; billing</h2><p>${active ? "Verified subscription status from Stripe." : snapshot.draftPlan ? "A checkout selection is saved; no paid plan is active." : "No paid subscription or checkout selection."}</p></div></div><div class="profile-plan-summary"><span>${active ? "Current plan" : snapshot.draftPlan ? "Checkout draft" : "Workspace access"}</span><strong>${esc(plan?.name || (auth.demo ? "Demo preview" : "No paid plan"))}</strong><small>${active ? `${esc(snapshot.subscription.status)} · ${esc(snapshot.subscription.cadence || "")}` : snapshot.draftPlan ? `${esc(snapshot.subscription.draft_cadence || "monthly")} · no charge made` : "Compare plans when ready"}</small></div><div class="account-card__actions"><a class="integration-card__btn integration-card__btn--primary" href="billing.html${auth.demo ? "?demo=1" : ""}">Open plans &amp; billing</a></div>`;
  document.getElementById("profile-workspace-card").innerHTML = `<div class="account-card__head"><span class="account-card__icon">WS</span><div><h2>Workspace context</h2><p>Tenant identity and reporting defaults shared by the team.</p></div></div><div class="profile-detail-list">${row("Workspace", workspace.name)}${row("Workspace ID", workspace.id)}${row("Your role", workspace.role)}${row("Members", workspace.memberCount)}${row("Timezone", snapshot.settings?.timezone)}${row("Currency", snapshot.settings?.currency)}${row("Default period", snapshot.settings?.default_period)}${row("Data retention", snapshot.settings?.data_retention_days ? `${snapshot.settings.data_retention_days} days` : "—")}</div><div class="account-card__actions"><a class="integration-card__btn" href="settings.html#workspace">Manage workspace</a></div>`;
  const connected = Boolean(meta?.connection?.accountId) || auth.demo;
  document.getElementById("profile-data-card").innerHTML = `<div class="account-card__head"><span class="account-card__icon">DATA</span><div><h2>Connected data</h2><p>${auth.demo ? "This preview never reads a live Meta account." : connected ? "Live Meta evidence is available to this workspace." : "Meta Ads needs connection or re-authorization."}</p></div></div><div class="profile-data-status"><span class="overview-signal overview-signal--${connected ? "positive" : "warning"}"></span><strong>${auth.demo ? "Demo sample data" : connected ? "Meta Ads connected" : "Setup required"}</strong></div><div class="profile-detail-list">${row("Account", auth.demo ? "Sample Meta account" : meta?.connection?.accountName || "—")}${row("Account ID", auth.demo ? "Demo only" : meta?.connection?.accountId || "—")}${row("Currency", auth.demo ? "USD" : meta?.connection?.currency || "—")}${row("Last connection update", auth.demo ? "Not applicable" : date(meta?.connection?.updatedAt))}</div><div class="account-card__actions"><a class="integration-card__btn" href="integrations.html${auth.demo ? "?demo=1" : ""}">Manage integrations</a></div>`;
  const session = auth.demo ? null : getSession();
  document.getElementById("profile-security-card").innerHTML = `<div class="account-card__head"><span class="account-card__icon">SEC</span><div><h2>Account security</h2><p>${auth.demo ? "No live account session is used in demo mode." : "Supabase Auth verifies and refreshes this browser session."}</p></div></div><div class="profile-detail-list">${row("Authentication", auth.demo ? "Demo preview" : "Supabase Auth")}${row("Account created", date(snapshot.user?.createdAt))}${row("Session issued", date(session?.issuedAt))}${row("Session expires", session?.expiresAt ? date(session.expiresAt) : "Managed by Supabase")}${row("Platform access", snapshot.platformAdmin?.role || "Customer workspace")}</div><p class="account-card__note">API keys and provider tokens never belong in profile fields or support messages.</p><div class="account-card__actions"><a class="integration-card__btn" href="settings.html#security">Security settings</a><button class="integration-card__btn integration-card__btn--danger" id="profile-sign-out-btn" type="button">${auth.demo ? "Exit demo" : "Sign out"}</button></div>`;
  document.getElementById("profile-sign-out-btn")?.addEventListener("click", () => auth.demo ? location.assign("index.html") : signOutAndRedirect());
}

async function init() {
  wireCommonShell("profile"); const auth = await initAppPage("profile.html"); if (!auth.ok) return; setTopbarIdentity(auth.profile, false, auth.demo ? "Sample account" : "Authenticated account", auth.demo ? "demo" : "account");
  let snapshot; if (auth.demo) snapshot = demoSnapshot(auth.profile); else { const result = await fetchAccountCenter(); if (!result.ok) throw new Error(result.data?.message || "Account profile could not be loaded."); snapshot = result.data; }
  const metaResult = auth.demo ? { data: { connection: null } } : await fetchMetaConnection(); hydrate(snapshot, auth, metaResult.ok ? metaResult.data : {});
  document.getElementById("profile-edit-form")?.addEventListener("submit", async (event) => {
    event.preventDefault(); const button = event.currentTarget.querySelector('button[type="submit"]'); const feedback = document.getElementById("profile-save-feedback"); const fields = { displayName: document.getElementById("profile-display-name").value.trim(), companyName: document.getElementById("profile-company-name").value.trim(), roleTitle: document.getElementById("profile-role-title").value.trim(), phone: document.getElementById("profile-phone").value.trim(), locale: document.getElementById("profile-locale").value }; button.disabled = true; feedback.textContent = "Saving profile…";
    const result = auth.demo ? { ok: true, data: { ...snapshot, profile: { ...snapshot.profile, display_name: fields.displayName, company_name: fields.companyName, role_title: fields.roleTitle, phone: fields.phone, locale: fields.locale } } } : await updateAccountCenter("profile", fields); button.disabled = false;
    if (!result.ok) { feedback.textContent = result.data?.message || "Profile could not be saved."; feedback.className = "account-feedback account-feedback--error"; return; }
    snapshot = result.data; feedback.textContent = "Profile saved to your account."; feedback.className = "account-feedback"; hydrate(snapshot, auth, metaResult.ok ? metaResult.data : {}); setTopbarIdentity({ ...auth.profile, displayName: fields.displayName }, false, "Authenticated account", auth.demo ? "demo" : "account");
  });
}

init().catch((error) => { const main = document.getElementById("main-content"); if (main) main.innerHTML = `<section class="dashboard-section"><h2>Profile unavailable</h2><p class="dashboard-empty">${esc(error.message || "Could not load account profile.")}</p></section>`; });
